### ISSUE TITLE
Problem with running tests that use Mockito extension

### ISSUE THREAD

**Issue by zyxist** [sormuras/junit-platform-maven-plugin#30]
Hello! Thanks for the project, it's good to see that someone is actively working on improving the testing support for JPMS.

I'm trying to use the plugin inside my project, where I want to use JUnit Mockito extension as well. Unfortunately, I end up with the following exception:

```
[WARNING] [WORKER]   JUnit Jupiter:FlightRecorderBuilderTest:whenClock_givenDefaultFlightRecorder_thenCustomClockIsInstalled()
[WARNING] [WORKER]     MethodSource [className = com.example.mymodule.FlightRecorderBuilderTest, methodName = whenClock_givenDefaultFlightRecorder_thenCustomClockIsInstalled, methodParameterTypes = ']
[WARNING] [WORKER]     => java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
[WARNING] [WORKER]        org.mockito@2.23.4/org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:74)
[WARNING] [WORKER]        com.sun.proxy.$Proxy28.isTypeMockable(Unknown Source)
[WARNING] [WORKER]        org.mockito@2.23.4/org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:29)
[WARNING] [WORKER]        org.mockito@2.23.4/org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
[WARNING] [WORKER]        org.mockito@2.23.4/org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:238)
[WARNING] [WORKER]        org.mockito@2.23.4/org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:226)
[WARNING] [WORKER]        org.mockito@2.23.4/org.mockito.internal.MockitoCore.mock(MockitoCore.java:68)
[WARNING] [WORKER]        org.mockito@2.23.4/org.mockito.Mockito.mock(Mockito.java:1896)
[WARNING] [WORKER]        org.mockito@2.23.4/org.mockito.Mockito.mock(Mockito.java:1805)
[WARNING] [WORKER]        com.example.mymodule/com.example.mymodule.FlightRecorderBuilderTest.whenClock_givenDefaultFlightRecorder_thenCustomClockIsInstalled(FlightRecorderBuilderTest.java:46)
[WARNING] [WORKER]        [...]
```

This is my setup (versions defined in `<dependencyManagement>` of a parent POM):

```
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>de.sormuras.junit</groupId>
                <artifactId>junit-platform-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
        </dependency>
    </dependencies>
```

Dependency management:

```
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>de.sormuras.junit</groupId>
                <artifactId>junit-platform-maven-plugin</artifactId>
                <version>1.0.0-M5</version>
                <extensions>true</extensions>
            </plugin>
        </plugins>
    </build>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>5.4.0-M1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-mockito</artifactId>
                <version>5.4.0-M1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-junit-jupiter</artifactId>
                <version>2.23.4</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>3.11.1</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

I also have an empty `module-info.test` file inside the test directory. I tried to put a real `module-info.java`, but it turned out that IntelliJ IDEA does not understand it, so it's pretty useless right now.

What am I missing?

**Comment by zyxist** [comment]
I solved the first problem by adding `mockito-core` explicitly, although it's a bit ugly. After another trial, I end up with the following error:

```
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ mymodule ---
[DEBUG] Configuring mojo org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-compiler-plugin:3.8.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@21588809]
[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile' with basic configurator -->
[DEBUG]   (f) basedir = /home/zyxist/Projekty/mymodule
[DEBUG]   (f) buildDirectory = /home/zyxist/Projekty/mymodule/target
[DEBUG]   (f) compilePath = [/home/zyxist/Projekty/mymodule/target/classes, /home/zyxist/.m2/repository/org/slf4j/slf4j-api/1.8.0-beta2/slf4j-api-1.8.0-beta2.jar]
[DEBUG]   (f) compileSourceRoots = [/home/zyxist/Projekty/mymodule/src/test/java]
[DEBUG]   (f) compilerId = javac
[DEBUG]   (f) debug = true
[DEBUG]   (f) failOnError = true
[DEBUG]   (f) failOnWarning = false
[DEBUG]   (f) forceJavacCompilerUse = false
[DEBUG]   (f) fork = false
[DEBUG]   (f) generatedTestSourcesDirectory = /home/zyxist/Projekty/mymodule/target/generated-test-sources/test-annotations
[DEBUG]   (f) mojoExecution = org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile {execution: default-testCompile}
[DEBUG]   (f) optimize = false
[DEBUG]   (f) outputDirectory = /home/zyxist/Projekty/mymodule/target/test-classes
[DEBUG]   (f) parameters = false
[DEBUG]   (f) project = MavenProject: com.example.mymodule:mymodule:1.0.0-SNAPSHOT @ /home/zyxist/Projekty/mymodule/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@5cbd159f
[DEBUG]   (f) showDeprecation = false
[DEBUG]   (f) showWarnings = false
[DEBUG]   (f) skipMultiThreadWarning = false
[DEBUG]   (f) source = 11
[DEBUG]   (f) staleMillis = 0
[DEBUG]   (s) target = 11
[DEBUG]   (f) testPath = [/home/zyxist/Projekty/mymodule/target/test-classes, /home/zyxist/Projekty/mymodule/target/classes, /home/zyxist/.m2/repository/org/slf4j/slf4j-api/1.8.0-beta2/slf4j-api-1.8.0-beta2.jar, /home/zyxist/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.3.2/junit-jupiter-api-5.3.2.jar, /home/zyxist/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar, /home/zyxist/.m2/repository/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar, /home/zyxist/.m2/repository/org/junit/platform/junit-platform-commons/1.3.2/junit-platform-commons-1.3.2.jar, /home/zyxist/.m2/repository/org/mockito/mockito-junit-jupiter/2.23.4/mockito-junit-jupiter-2.23.4.jar, /home/zyxist/.m2/repository/org/mockito/mockito-core/2.23.4/mockito-core-2.23.4.jar, /home/zyxist/.m2/repository/net/bytebuddy/byte-buddy/1.9.3/byte-buddy-1.9.3.jar, /home/zyxist/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.3/byte-buddy-agent-1.9.3.jar, /home/zyxist/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar, /home/zyxist/.m2/repository/org/assertj/assertj-core/3.11.1/assertj-core-3.11.1.jar, /home/zyxist/.m2/repository/de/sormuras/junit/junit-platform-isolator-worker/1.0.0-M10/junit-platform-isolator-worker-1.0.0-M10.jar, /home/zyxist/.m2/repository/de/sormuras/junit/junit-platform-isolator/1.0.0-M10/junit-platform-isolator-1.0.0-M10.jar]
[DEBUG]   (f) useIncrementalCompilation = true
[DEBUG]   (f) verbose = false
[DEBUG] -- end configuration --
[DEBUG] Using compiler 'javac'.
[DEBUG] Adding /home/zyxist/Projekty/mymodule/target/generated-test-sources/test-annotations to test-compile source roots:
  /home/zyxist/Projekty/mymodule/src/test/java
[DEBUG] New test-compile source roots:
  /home/zyxist/Projekty/mymodule/src/test/java
  /home/zyxist/Projekty/mymodule/target/generated-test-sources/test-annotations
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- junit-platform-maven-plugin:1.0.0-M5:launch (injected-launch) @ mymodule ---
[DEBUG] Configuring mojo de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5:launch from plugin realm ClassRealm[extension>de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@21588809]
[DEBUG] Configuring mojo 'de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5:launch' with basic configurator -->
[DEBUG]   (f) dryRun = false
[DEBUG]   (f) executor = DIRECT
[DEBUG]   (f) isolation = MERGED
[DEBUG]   (f) mavenBuild = org.apache.maven.model.Build@13fed1ec
[DEBUG]   (f) mavenProject = MavenProject: com.example.mymodule:mymodule:1.0.0-SNAPSHOT @ /home/zyxist/Projekty/mymodule/pom.xml
[DEBUG]   (f) mavenRepositorySession = org.eclipse.aether.DefaultRepositorySystemSession@61c42416
[DEBUG]   (f) mavenSession = org.apache.maven.execution.MavenSession@5cbd159f
[DEBUG]   (f) skip = false
[DEBUG]   (f) targetDirectory = /home/zyxist/Projekty/mymodule/target/junit-platform
[DEBUG]   (f) timeout = 300
[DEBUG] -- end configuration --
[DEBUG] Executing JUnitPlatformMojo...
[INFO] Launching JUnit Platform 1.3.2...
[DEBUG] Path
[DEBUG]   java.home = /usr/lib/jvm/java-11-openjdk
[DEBUG]   user.dir = /home/zyxist/Projekty/mymodule
[DEBUG]   project.basedir = /home/zyxist/Projekty/mymodule
[DEBUG] Class Loader
[DEBUG]   mojo's loader = ClassRealm[extension>de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@21588809]
[DEBUG]   context loader = ClassRealm[extension>de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@21588809]
[DEBUG]   platform loader = jdk.internal.loader.ClassLoaders$PlatformClassLoader@19ee1ae6
[DEBUG] Artifact Map
[DEBUG]   de.sormuras.junit:junit-platform-isolator          -> de.sormuras.junit:junit-platform-isolator:jar:1.0.0-M10:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, de.sormuras.junit:junit-platform-isolator-worker:jar:1.0.0-M10, de.sormuras.junit:junit-platform-isolator:jar:1.0.0-M10]
[DEBUG]   de.sormuras.junit:junit-platform-isolator-worker   -> de.sormuras.junit:junit-platform-isolator-worker:jar:1.0.0-M10:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, de.sormuras.junit:junit-platform-isolator-worker:jar:1.0.0-M10]
[DEBUG]   net.bytebuddy:byte-buddy                           -> net.bytebuddy:byte-buddy:jar:1.9.3:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.mockito:mockito-core:jar:2.23.4, net.bytebuddy:byte-buddy:jar:1.9.3]
[DEBUG]   net.bytebuddy:byte-buddy-agent                     -> net.bytebuddy:byte-buddy-agent:jar:1.9.3:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.mockito:mockito-core:jar:2.23.4, net.bytebuddy:byte-buddy-agent:jar:1.9.3]
[DEBUG]   org.apiguardian:apiguardian-api                    -> org.apiguardian:apiguardian-api:jar:1.0.0:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.junit.jupiter:junit-jupiter-api:jar:5.3.2, org.apiguardian:apiguardian-api:jar:1.0.0]
[DEBUG]   org.assertj:assertj-core                           -> org.assertj:assertj-core:jar:3.11.1:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.assertj:assertj-core:jar:3.11.1]
[DEBUG]   org.junit.jupiter:junit-jupiter-api                -> org.junit.jupiter:junit-jupiter-api:jar:5.3.2:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.junit.jupiter:junit-jupiter-api:jar:5.3.2]
[DEBUG]   org.junit.platform:junit-platform-commons          -> org.junit.platform:junit-platform-commons:jar:1.3.2:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.junit.jupiter:junit-jupiter-api:jar:5.3.2, org.junit.platform:junit-platform-commons:jar:1.3.2]
[DEBUG]   org.mockito:mockito-core                           -> org.mockito:mockito-core:jar:2.23.4:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.mockito:mockito-core:jar:2.23.4]
[DEBUG]   org.mockito:mockito-junit-jupiter                  -> org.mockito:mockito-junit-jupiter:jar:2.23.4:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.mockito:mockito-junit-jupiter:jar:2.23.4]
[DEBUG]   org.objenesis:objenesis                            -> org.objenesis:objenesis:jar:2.6:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.mockito:mockito-core:jar:2.23.4, org.objenesis:objenesis:jar:2.6]
[DEBUG]   org.opentest4j:opentest4j                          -> org.opentest4j:opentest4j:jar:1.1.1:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.junit.jupiter:junit-jupiter-api:jar:5.3.2, org.opentest4j:opentest4j:jar:1.1.1]
[DEBUG]   org.slf4j:slf4j-api                                -> org.slf4j:slf4j-api:jar:1.8.0-beta2:provided trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, org.slf4j:slf4j-api:jar:1.8.0-beta2]
[DEBUG] Version
[DEBUG]   java.version = 11.0.1
[DEBUG]   java.class.version = 55.0
[DEBUG]   isolator.version = 1.0.0-M10
[DEBUG]   junit.platform.version = 1.3.2
[DEBUG]   junit.jupiter.version = 5.3.2
[DEBUG]   junit.vintage.version = 5.3.2
[DEBUG] Java Module System
[DEBUG]   main -> module com.example.mymodule { requires=[java.base, org.slf4j] packages=[com.example.mymodule.meta, com.example.mymodule.gems, com.example.mymodule.sources, com.example.mymodule.exception, com.example.mymodule.utils, com.example.mymodule.api] }
[DEBUG]   test -> <empty>
[DEBUG]   mode -> MODULAR_PATCHED_TEST_RUNTIME
[DEBUG]   module-info.test -> /home/zyxist/Projekty/mymodule/src/test/java/module-info.test
[DEBUG] Resolving artifact org.junit.platform:junit-platform-launcher:jar:1.3.2 from [central (https://repo.maven.apache.org/maven2, default, releases), central (https://repo.maven.apache.org/maven2, default, releases)]...
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=7, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=5, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=0, ConflictResolver.conflictItemCount=7, DefaultDependencyCollector.collectTime=2, DefaultDependencyCollector.transformTime=0}
[DEBUG] Resolving artifact org.junit.jupiter:junit-jupiter-engine:jar:5.3.2 from [central (https://repo.maven.apache.org/maven2, default, releases), central (https://repo.maven.apache.org/maven2, default, releases)]...
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=11, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=6, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=0, ConflictResolver.conflictItemCount=11, DefaultDependencyCollector.collectTime=2, DefaultDependencyCollector.transformTime=0}
[DEBUG] Resolving artifact org.junit.jupiter:junit-jupiter-engine:jar:5.3.2 from [central (https://repo.maven.apache.org/maven2, default, releases), central (https://repo.maven.apache.org/maven2, default, releases)]...
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=0, ConflictMarker.markTime=0, ConflictMarker.nodeCount=11, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=6, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=0, ConflictResolver.conflictItemCount=11, DefaultDependencyCollector.collectTime=2, DefaultDependencyCollector.transformTime=0}
[DEBUG] No custom selector was configured, providing default one...
[DEBUG] Isolator Path Layering
[DEBUG] merged(test+main)
[DEBUG]   junit-jupiter-api-5.3.2.jar                        -> /home/zyxist/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.3.2/junit-jupiter-api-5.3.2.jar
[DEBUG]   apiguardian-api-1.0.0.jar                          -> /home/zyxist/.m2/repository/org/apiguardian/apiguardian-api/1.0.0/apiguardian-api-1.0.0.jar
[DEBUG]   opentest4j-1.1.1.jar                               -> /home/zyxist/.m2/repository/org/opentest4j/opentest4j/1.1.1/opentest4j-1.1.1.jar
[DEBUG]   junit-platform-commons-1.3.2.jar                   -> /home/zyxist/.m2/repository/org/junit/platform/junit-platform-commons/1.3.2/junit-platform-commons-1.3.2.jar
[DEBUG]   mockito-junit-jupiter-2.23.4.jar                   -> /home/zyxist/.m2/repository/org/mockito/mockito-junit-jupiter/2.23.4/mockito-junit-jupiter-2.23.4.jar
[DEBUG]   mockito-core-2.23.4.jar                            -> /home/zyxist/.m2/repository/org/mockito/mockito-core/2.23.4/mockito-core-2.23.4.jar
[DEBUG]   byte-buddy-1.9.3.jar                               -> /home/zyxist/.m2/repository/net/bytebuddy/byte-buddy/1.9.3/byte-buddy-1.9.3.jar
[DEBUG]   byte-buddy-agent-1.9.3.jar                         -> /home/zyxist/.m2/repository/net/bytebuddy/byte-buddy-agent/1.9.3/byte-buddy-agent-1.9.3.jar
[DEBUG]   objenesis-2.6.jar                                  -> /home/zyxist/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar
[DEBUG]   assertj-core-3.11.1.jar                            -> /home/zyxist/.m2/repository/org/assertj/assertj-core/3.11.1/assertj-core-3.11.1.jar
[DEBUG]   junit-platform-isolator-worker-1.0.0-M10.jar       -> /home/zyxist/.m2/repository/de/sormuras/junit/junit-platform-isolator-worker/1.0.0-M10/junit-platform-isolator-worker-1.0.0-M10.jar
[DEBUG]   junit-platform-isolator-1.0.0-M10.jar              -> /home/zyxist/.m2/repository/de/sormuras/junit/junit-platform-isolator/1.0.0-M10/junit-platform-isolator-1.0.0-M10.jar
[DEBUG]   patched-test-runtime                               -> /home/zyxist/Projekty/mymodule/target/junit-platform/patched-test-runtime
[DEBUG]   slf4j-api-1.8.0-beta2.jar                          -> /home/zyxist/.m2/repository/org/slf4j/slf4j-api/1.8.0-beta2/slf4j-api-1.8.0-beta2.jar
[DEBUG] launcher
[DEBUG]   junit-platform-launcher-1.3.2.jar                  -> /home/zyxist/.m2/repository/org/junit/platform/junit-platform-launcher/1.3.2/junit-platform-launcher-1.3.2.jar
[DEBUG]   junit-platform-engine-1.3.2.jar                    -> /home/zyxist/.m2/repository/org/junit/platform/junit-platform-engine/1.3.2/junit-platform-engine-1.3.2.jar
[DEBUG]   junit-jupiter-engine-5.3.2.jar                     -> /home/zyxist/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.3.2/junit-jupiter-engine-5.3.2.jar
[DEBUG] Selected test module(s) present: [com.example.mymodule]

[ERROR] Failed to execute goal de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5:launch (injected-launch) on project mymodule: Execution failed! java.lang.ClassNotFoundException: de.sormuras.junit.platform.isolator.worker.Worker -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5:launch (injected-launch) on project mymodule: Execution failed!
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Execution failed!
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.executeDirect(JUnitPlatformMojo.java:441)
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.execute(JUnitPlatformMojo.java:424)
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.execute(JUnitPlatformMojo.java:411)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassNotFoundException: de.sormuras.junit.platform.isolator.worker.Worker
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.executeDirect(JUnitPlatformMojo.java:436)
	... 25 more
Caused by: java.lang.ClassNotFoundException: de.sormuras.junit.platform.isolator.worker.Worker
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/jdk.internal.loader.Loader.loadClass(Loader.java:544)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at de.sormuras.junit.platform.isolator.Isolator.evaluate(Isolator.java:66)
	at de.sormuras.junit.platform.maven.plugin.JUnitPlatformMojo.lambda$executeDirect$7(JUnitPlatformMojo.java:434)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

My updated dependencies:

```
    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
        </dependency>
    </dependencies>
```

Note - in the `<dependencyManagement>` section of the parent POM I have also:

```
            <dependency>
                <groupId>io.projectreactor</groupId>
                <artifactId>reactor-bom</artifactId>
                <version>Bismuth-RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Comment by sormuras** [comment]
> Hello! Thanks for the project, it's good to see that someone is actively working on improving the testing support for JPMS.

@zyxist thanks for the feedback!

So, let's start debugging. First, configure the plugin to let the console launcher care about starting the test run via [`<executor>JAVA</executor>`](https://github.com/sormuras/junit-platform-maven-plugin#executor). Does it help?

Now to the underlying issue: I'm wondering why `de.sormuras.junit:junit-platform-isolator-worker` is part your project's dependencies. The `-worker` artifact should be here at all, it is resolved at runtime.
```
[DEBUG] Artifact Map
[DEBUG]   de.sormuras.junit:junit-platform-isolator          -> de.sormuras.junit:junit-platform-isolator:jar:1.0.0-M10:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, de.sormuras.junit:junit-platform-isolator-worker:jar:1.0.0-M10, de.sormuras.junit:junit-platform-isolator:jar:1.0.0-M10]
[DEBUG]   de.sormuras.junit:junit-platform-isolator-worker   -> de.sormuras.junit:junit-platform-isolator-worker:jar:1.0.0-M10:test trail=[com.example.mymodule:mymodule:jar:1.0.0-SNAPSHOT, de.sormuras.junit:junit-platform-isolator-worker:jar:1.0.0-M10]
...
```
I can spot it in line `[DEBUG]   (f) testPath = [/home/zyxist/Pro...` of `maven-compiler-plugin:3.8.0:testCompile` already. That's way too early...

**Comment by zyxist** [comment]
Regarding `-worker` artifact - this was my intentional addition as an attempt to solve the issue on my own. It doesn't solve the problem, and the plugin throws exactly the same exception regardless of that.

Here's the example that reproduces the issue: https://github.com/zyxist/junit-jpms-mockito-example

**Comment by sormuras** [comment]
Got your example project compiling and running tests (Maven + IDEA). PR inc...

An empty `module-info.test` is not valid and never enough to get `MODULAR_PATCHED_TEST_RUNTIME` mode to work. You basically need to tell the Java module system the same configuration as if you wrote a dedicated _test_ module.

Btw. Mockito only defined an automatic module name for `org.mockito:mockito-core`, namely: `org.mockito`
The Mockito Jupiter extension `org.mockito:mockito-junit-jupiter` lacks such a well-formed name it's manifest file.

/cc @raphw

**Comment by sormuras** [comment]
> I also have an **empty** `module-info.test` file inside the test directory. I tried to put a real `module-info.java`, but it turned out that IntelliJ IDEA does not understand it, so it's pretty useless right now.

Using this `module-info.test` it works:

```
// open module com.example.foo {
//   requires org.junit.jupiter.api;
//	 requires org.mockito;
//   requires mockito.junit.jupiter; // automatic module name derived from jar file name
//   requires net.bytebuddy;
// }

// "open module" (each package) to JUnit to find non-public tests
--add-opens
  com.example.foo/com.example.foo=org.junit.platform.commons
// "open module" (each package) to Mockito to access non-public fields
--add-opens
  com.example.foo/com.example.foo=org.mockito

// "requires <module name>"
--add-reads
  com.example.foo=org.junit.jupiter.api
--add-reads
  com.example.foo=org.mockito
--add-reads
  com.example.foo=mockito.junit.jupiter
--add-reads
  com.example.foo=net.bytebuddy
```

**Comment by sormuras** [comment]
Could you solve the issue @zyxist ?

**Comment by zyxist** [comment]
Hello, sorry for the late reply. I have checked and merged the solution to my example - thanks for the help. I had trouble with finding information, what exactly should be put into `module-info.test`, and the error message did not help. Now things are more clear.

**Comment by sormuras** [comment]
You're welcome!

And feel free and invited to improve the `module-info.test` section here: https://github.com/sormuras/sormuras.github.io/blob/master/blog/2018-09-11-testing-in-the-modular-world.md#white-box-modular-testing-with-extra-java-command-line-options

**Comment by TomerFi** [comment]
Hey @sormuras 
Sorry to barge in onto a closed issue.

I have an (unrelated) issue getting this plugin to work with a non-modular project converted modular.
It screams about inaccessible private fields and `ByteBuddy` classes not found.
I've tried to tackle this issue bymyself, but to no avail so far.

I figured I'll start a new project from scratch and try to figure it out,
So I went back to basics and found this issue.

As it turns out,
Bumping `junit-jupiter-api` to 5.5.x or newer breaks @zyxist  example.

I've forked @zyxist example and added a test workflow:

- [working with the original 5.4.0-RC1](https://github.com/TomerFi/junit-jpms-mockito-example/runs/1605438681?check_suite_focus=true)
- [working after bumping to 5.4.2](https://github.com/TomerFi/junit-jpms-mockito-example/runs/1605438681?check_suite_focus=true)
- [not working after bumping to 5.5.0-RC1](https://github.com/TomerFi/junit-jpms-mockito-example/runs/1605459132?check_suite_focus=true) (or newer versions for that manner).

The error is:

``` shell
Error:  Failed to execute goal de.sormuras.junit:junit-platform-maven-plugin:1.0.0-M5:launch (injected-launch) on project modular-test: Execution failed!: java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory: org.junit.platform.launcher.core.LauncherFactory -> [Help 1]
```

Unfortunately, it doesn't help me with my own issue,
but I figured I'll run it by you anyway.

Thank you very much for this great plugin!

**Comment by TomerFi** [comment]
I've tried updating everything:
Compiler plugin - 3.8.0 > 3.8.1
Junit Platform plugin - 1.0.0-M5 > 1.1.0
Mockito dependency - 2.23.4 > 3.6.28
Junit dependency - 5.5.0-RC1 > 5.7.0

The [result](https://github.com/TomerFi/junit-jpms-mockito-example/runs/1605538363?check_suite_focus=true) if the same.

**Comment by TomerFi** [comment]
Oh, I see now there is already an [open issue](https://github.com/sormuras/junit-platform-maven-plugin/issues/39#issuecomment-636481223) where you acknowledged the `junit 5.4.x` compatibility issue.
So... there was no need for me to barge in on this closed one.
I'll watch over the open issue for a fix.

Thanks again for this great plugin.

**Comment by sormuras** [comment]
2021 will be the year of `junit-platform-maven-plugin` ... `2.0` 😉
